name: Food App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -la

      - name: Build Success
        run: echo "Multi-Restaurant Menu App build successful"